apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

images:
- name: shilucloud/sigstore-app
  newName: docker.io/shilucloud/sigstore-app
  newTag: main-1fb4a0c375419dc46897e78115727d56a4dde179

replicas:
- count: 1
  name: sigstore-app
