apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

images:
- name: shilucloud/sigstore-app
  newName: docker.io/shilucloud/sigstore-app
  newTag: main-44c7492a9881b2bd83d79525b88c171ed4d93985

replicas:
- count: 1
  name: sigstore-app
