apiVersion: v1
kind: Namespace
metadata:
  name: sigstore-app-dev
  labels:
    app.kubernetes.io/name: sigstore-app-dev
    app.kubernetes.io/instance: sigstore-app-dev
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: namespace
    policy.sigstore.dev/include: true