apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-stage
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.slack: deployments
    argo-cd.argoproj.io/sync-wave: "2"

spec:
  project: default

  source:
    repoURL: https://github.com/shilucloud/sigstore-gitops
    targetRevision: main
    path: apps/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: sigstore-app-stage

  syncPolicy:
    automated:
      prune: true          # remove resources deleted from git
      selfHeal: true       # revert manual kubectl changes
    syncOptions:
      - CreateNamespace=true
