apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: github-keyless-only

spec:
  mode: enforce

  images:
    - glob: "index.docker.io/shilucloud/sigstore-app*"

  authorities:
    - name: github-actions
      keyless:
        url: https://fulcio.sigstore.dev

        identities:
          - issuer: https://token.actions.githubusercontent.com
            subject: https://github.com/shilucloud/sigstore-app/.github/workflows/main.yaml@refs/heads/main