apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

replicas:
- count: 1
  name: sigstore-app
images:
- name: shilucloud/sigstore-app
  newName: docker.io/shilucloud/sigstore-app
  newTag: v0.0.2
